config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index, :new, :create]
  delete "/users/:id", to: "users#destroy", as: "destroy_user"

  resources :ingredients, only: [:index, :show, :new, :create]
  delete "/ingredients/:id", to: "ingredients#destroy", as: "destroy_ingredient"

  resources :recipes, only: [:index, :show, :new, :create]

  resources :rec_ings, only: [:new, :create]
end

app/models/allergy.rb
class Allergy < ApplicationRecord
    belongs_to :user
    belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :rec_ings
    has_many :recipes, through: :rec_ings 

    has_many :allergies
    has_many :users, through: :allergies

end

app/models/rec_ing.rb
class RecIng < ApplicationRecord
    belongs_to :ingredient
    belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user

    has_many :rec_ings
    has_many :ingredients, through: :rec_ings
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
    
    has_many :allergies
    has_many :ingredients, through: :allergies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    # before_action find, only: [:show, ]

    def index
        @ingredients = Ingredient.all
    end

    def show
        @ingredient = Ingredient.find(params[:id])
    end

    def new
        @ingredient = Ingredient.new
    end

    def create
        @ingredient = Ingredient.create(ingredient_params)
        redirect_to ingredient_path(@ingredient)
    end

    def destroy
        @ingredient = Ingredient.find(params[:id])
        @ingredient.destroy
        redirect_to ingredients_path
    end

    private
    def find
        @ingredient = Ingredient.find(ingredient_params)
    end

    def ingredient_params
        params.require(:ingredient).permit(:name)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    
    def index
        @recipes = Recipe.all
    end

    def show
        @recipe = Recipe.find(params[:id])
        #@quantity = RecIng.find_by(recipe_id: @recipe.id, ingredient_id: ri.id).ing_quantity
    end

    def new
        @recipe = Recipe.new
        @recipe.rec_ings.build
    end

    def create
        byebug
        @recipe = Recipe.create(recipe_params)
        
        redirect_to recipe_path(@recipe)
    end

    private

    def recipe_params
        params.require(:recipe).permit(:name, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        redirect_to user_path(@user)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end


    private
    def user_params
        params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<h1>Index</h1>

<ul>
<% @ingredients.each do |i| %>
    <li><%= link_to i.name, ingredient_path(i) %></li>
<% end %>
</ul>

<%= link_to "Create New Ingredient", new_ingredient_path %>

app/views/ingredients/new.html.erb
<%= form_for @ingredient do |i| %>
    <%= i.label :name %>
    <%= i.text_field :name %>
    <%= i.submit %>
<% end %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>

<h2>Found in the Following Recipes: </h2>
<ul>
<% @ingredient.recipes.each do |ir| %>
    <li>
    <%= link_to ir.name, recipe_path(ir) %>
    </li>
<% end %>
</ul>
<%= link_to "Back to Index", ingredients_path %>
<%= link_to "Delete Ingredient", destroy_ingredient_path, method: "DELETE" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>

<ul>
    <% @recipes.each do |rec| %>
        <li>
            <%= link_to rec.name, recipe_path(rec) %>
        </li>
        <% end %>
</ul>

<%= link_to "Create a New Recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe Form</h1>

<%= form_for @recipe do |r| %>
    <%= r.label :name %>
    <%= r.text_field :name %>
    <%= r.label :user_id %>
    <%= r.collection_select :user_id, User.all, :id, :name %>
    
    <%= fields_for :rec_ings do |ri|%>
        <% ri.label :recipe_id %>
        <% ri.number_field :name, :value => @recipe.id %>
        <br>
        <div>
        <%= ri.label :ing_quantity, "Quantity" %>
        <%= ri.number_field :ing_quantity %>
        <%= ri.label :ingredient_id %>
        <%= ri.collection_select :ingredient_id, Ingredient.all, :id, :name %>
        </div>
    <% end %>

    <%= r.submit %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Recipe Author: <%= link_to @recipe.user.name, user_path(@recipe.user) %></h2>

<h3>Ingredients:</h3>
<ul>
    <% @recipe.ingredients.each do |ri| %>
    <li>
        <%= RecIng.find_by(recipe_id: @recipe.id, ingredient_id: ri.id).ing_quantity %> <%= link_to ri.name + "(s)", ingredient_path(ri) %>
    </li>
    <% end %>
</ul>

<%= link_to "Back to Index", recipes_path %>

app/views/users/index.html.erb
<h1>All the Users</h1>

<ul>
    <% @users.each do |u| %>
        <li><%= link_to u.name, user_path(u) %></li>
    <% end %>
</ul>

<%= link_to "Create New User", new_user_path %>

app/views/users/new.html.erb
<%= form_for @user do |u|%>
    <%= u.label :name%>
    <%= u.text_field :name %>
    <%= u.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h2>Recipes :</h2>
<ul>
    <% @user.recipes.each do |rec| %>
        <li>
        <%= link_to rec.name, recipe_path(rec) %>
        </li>
    <% end %>
</ul>
<h2>Allergic to: </h2>
<ul>
    <% @user.allergies.each do |a| %>
        <li>
        <%= link_to a.ingredient.name, ingredient_path(a.ingredient) %>
        </li>
    <% end %>
</ul>

<%= link_to "Back to Index", users_path %>
<%= link_to "Delete User", destroy_user_path, method: "DELETE" %>